version: '3.8'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    environment:
      - PHP_FPM_HOST=php-fpm-app
    # volumes:
      # - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm-app
    networks:
      - app-network

  php-fpm-app:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - .env:/var/www/html/.env
    expose:
      - "9000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
